config/routes.rb
Rails.application.routes.draw do
  root to: "cocktails#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [:new, :create]
  end
  delete "/doses/:id", to: "doses#destroy", as: "dose"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail_id, presence: true
  validates :ingredient_id, presence: true
  validates_uniqueness_of :cocktail_id, :scope => [:ingredient_id]
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  before_action :set_cocktail, only: [:show]

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def show
    @dose = Dose.new
  end

  def index
    @cocktails = Cocktail.all
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  before_action :set_cocktail, only: [:new, :create]

  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail_id = @cocktail.id
    if @dose.save
      redirect_to cocktail_path(@dose.cocktail_id)
    else
      render :new
    end
  end

  def index
    redirect_to cocktails_path
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://res.cloudinary.com/logicisaliar/image/upload/v1529101646/Cocktails.jpg');">
  <div class="banner-content">
    <h1>Cocktailmania</h1>
    <p>
      <span id="banner-typed-text"></span>
    </p>

  </div>
</div>


<%#= cl_image_tag(cocktail.photo,
width: 400, height: 300, crop: :fill) %>

<div class="container">
  <div class="btn margin-bottom" >
<%= link_to "Add a new cocktail", new_cocktail_path  %>
</div>

  <div class="row"></div>
  <% @cocktails.each do |cocktail| %>
  <div class="col-xs-12 col-md-4">
    <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path(cocktail.photo,
width: 150, height: 150, crop: :thumb, gravity: :face) %>')">
      <div class="card-category">
        <h2><%= link_to cocktail.name, cocktail_path(cocktail)%> </h2>
      </div>
    </div>
  <!-- <div class="card-description">
    <h2>B</h2>
    <p>C</p>
  </div> -->
  <!-- <a class="card-link" href="#" ></a> -->
</div>
<% end %>
</div>

app/views/cocktails/new.html.erb
<%= simple_form_for @cocktail do |f| %>
<%= f.input :name %>
<%= f.input :photo %>
<%= f.input :photo_cache, as: :hidden %>
<%= f.submit "Add the cocktail", class: "btn" %>
<% end %>

app/views/cocktails/show.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://res.cloudinary.com/logicisaliar/image/upload/v1529101646/Cocktails.jpg');">
  <div class="container" id="show">
    <h1><%= @cocktail.name %></h1>


  <%= link_to "Go back", cocktails_path  %>

  <!-- @ingredients = Ingredient.all -->
<div class="card">
  <div class="table-responsive">
  <table class="table-hover">
    <tr>
      <th> <stong>Ingredients   </stong></th>
      <th><em>Description</em></th>
      <th>Delete?</th>
    </tr>
    <% @cocktail.doses.each do |dose| %>
      <tr>
        <td>
          <%= dose.ingredient.name %> </td>
          <td> <%= dose.description %> </td>
          <td> <%= link_to " Delete x", dose_path(dose.id),
          method: :delete,
          data: { confirm: "Are you sure?" }  %>
        </td>
        </tr>
      <% end %>
    </table>
    </div>
    </div>
    <div class="card">
      <%= image_tag @cocktail.photo.url(:bright_face) %>
      <%= simple_form_for [@cocktail, @dose] do |f| %>
      <%= f.association :ingredient, include_hidden: false %>
      <%= f.input :description %>
  <%#= link_to "Add ingredient and dosage description", new_cocktail_dose_path(@cocktail) %>

      <%= f.submit "Add info", class: "btn margin-bottom" %>
      <% end %>
    </div>
  </div>
  </div>

app/views/doses/create.html.erb
<h1>Doses#create</h1>
<p>Find me in app/views/doses/create.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsMisterCocktail</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">


  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

      <%= yield %>
<%= javascript_pack_tag('application.js') %>
</body>
</html>